#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

mvn install:install-file -Dfile=../../jbossas-7/repo/caching-1.0.jar -DgroupId=org.judcon -DartifactId=caching -Dversion=1.0 -Dpackaging=jar

mvn install:install-file -Dfile=../../jbossas-7/repo/deployments/OrderService.jar -DgroupId=org.switchyard.quickstarts.demos -DartifactId=switchyard-quickstart-demo-multi-artifacts -Dversion=0.7.0.Final -Dpackaging=jar
